name: uas_exchange_android_smt5
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_cli: ^1.8.1
  banner_carousel: ^1.2.1
  sweet_nav_bar: ^1.0.5
  syncfusion_flutter_datepicker: ^20.4.50
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

